# based off https://github.com/jalessio/ansible-role-ros
# run locally with "ansible-playbook -i "localhost," -c local dev_computer_playbook.yml"
---
- hosts: localhost
  tasks:
    - include: ros_init.yml

    - name: install ros packages
      become: yes
      apt: pkg=ros-kinetic-{{ item }} state=latest update_cache=true
      with_items:
        - desktop

    - include: common_tasks.yml
