# Common tasks for NRMC2018
---
- name: add ZR300 key
  become: yes
  apt_key: keyserver=keys.gnupg.net id=0xD6FB2970

- name: add ZR300 repository
  become: yes
  apt_repository: repo='deb http://realsense-alm-public.s3.amazonaws.com/apt-repo xenial main' state=present

- name: add mraa key
  become: yes
  apt_key: keyserver=keyserver.ubuntu.com id=39B88DE4

- name: add mraa repository
  become: yes
  apt_repository: repo='deb http://ppa.launchpad.net/mraa/mraa/ubuntu xenial main' state=present

- name: add mraa src repository
  become: yes
  apt_repository: repo='deb-src http://ppa.launchpad.net/mraa/mraa/ubuntu xenial main' state=present

- name: install other packages
  become: yes
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - build-essential
    - google-mock
    - clang-format-3.6
    - can-utils 
    - ssh
    - libopencv-dev
    - librealsense-dev
    - librealsense-utils
    - libbluetooth-dev
    - python-numpy
    - python-pip
    - libmraa1 
    - libmraa-dev

- name: add imutils
  become: yes
  pip: name=imutils

- pip:
    name: wheel

- pip:
    name: multiprocessing

- name: get and unpack imu runtime
  become: no
  unarchive:
    src: https://bitbucket.org/lpresearch/openmat/downloads/LpSensor-1.3.5-Linux-x86-64.tar.gz
    dest: ./
    #remote_src: yes # for ansible version >= 2.2
    copy: no # for ansible version < 2.2

- name: install imu runtime
  become: yes
  apt:
    deb: ./LpSensor-1.3.5-Linux-x86-64/liblpsensor-1.3.5-Linux.deb

- name:  create gmock directory
  become: yes
  file: path=/usr/src/gmock/build state=directory

- name: install gmock
  become: yes
  shell: |
    pushd /usr/src/gmock/build
    sudo cmake ../
    sudo make
    popd
  args:
    executable: /bin/bash

- name: check if rosdep already initialized
  stat: 
    path: /etc/ros/rosdep/sources.list.d/20-default.list
  register: depcheck

- name: init rosdep
  become: yes
  command: /usr/bin/rosdep init
  when: depcheck.stat.exists == False

- name: get and unpack git-lfs
  unarchive:
    src: https://github.com/git-lfs/git-lfs/releases/download/v2.3.4/git-lfs-linux-amd64-2.3.4.tar.gz
    dest: ./
    copy: no

- name: install git-lfs
  become: yes
  shell: |
    pushd git-lfs-2.3.4
    sudo ./install.sh
    popd
    git lfs install
  args:
    executable: /bin/bash

- name: update rosdep
  command: /usr/bin/rosdep update

- name: run rosdep # this does not run cleanly, will report error on custom packages. Also doesn't seem to install anything, all dependencies seem to be installed by previous steps
  shell: |
    pushd {{ playbook_dir }}/../..
    rosdep install --from-paths . --ignore-src --rosdistro=kinetic --default-yes -r --os=ubuntu:xenial
    popd
  args:
    executable: /bin/bash

# clear the downloaded package files, do this at the end in case previous step fails
- name: cleanup imu
  become: no
  shell: /bin/rm -rf ./Lp*

- name: remove git-lfs files
  become: no
  shell: rm -rf  ./git-lfs*
