# based off https://github.com/jalessio/ansible-role-ros
# run locally with "ansible-playbook -i "localhost," -c local playbook.yml"
---
- hosts: localhost
  tasks:
    - name: Add ROS repository apt-key
      become: yes
      apt_key: keyserver=hkp://ha.pool.sks-keyservers.net:80 id=0xB01FA116

    - name: Add ROS repository
      become: yes
      apt_repository: repo='deb http://packages.ros.org/ros/ubuntu {{ ansible_distribution_release }} main' state=present

    - lineinfile:
        dest=~/.bashrc
        line="source /opt/ros/kinetic/setup.bash"

    #- name: update apt packages
    #  become: yes
    #  apt:  
    #    update_cache: yes
    #    upgrade: safe

    - name: install other packages
      become: yes
      apt: pkg={{ item }} state=latest update_cache=true
      with_items:
        - python-catkin-tools
        - tmux
        - vim-gnome
        - tree
        - google-mock
    
    - name: install gmock
      shell: ./gmock_setup.shv     
    
    - name: install ros packages
      become: yes
      apt: pkg=ros-kinetic-{{ item }} state=latest update_cache=true
      with_items:
        - desktop-full
   
    - name: install gmock
      shell: ./gmock_setup.shv
