#ifndef WHEEL_PARAMS_H
#define WHEEL_PARAMS_H

#define FRONT_LEFT_WHEEL_ID     4
#define FRONT_RIGHT_WHEEL_ID    1
#define BACK_RIGHT_WHEEL_ID     2
#define BACK_LEFT_WHEEL_ID      3
#define CENTRAL_DRIVE_ID        5
#define LINEAR_MOTOR_ID         6
#define VIBRATOR_MOTOR_ID       7
#define SMALL_CONVEYOR_ID       8
#define LARGE_CONVEYOR_ID       9
#define LEFT_OUTRIGGER_ID       10
#define RIGHT_OUTRIGGER_ID      11

#define WHEEL_CAN_NETWORK ("can0")

#define MAX_WHEEL_VELOCITY .5f
#define MAX_WHEEL_TORQUE 176.0f
#define WHEEL_GEAR_RATIO 181.4f
#define WHEEL_OUTPUT_RATIO .03048f
#define WHEEL_POLE_PAIRS 1
#define WHEEL_TORQUE_CONSTANT 4.0f

#define MAX_CENTRAL_DRIVE_VELOCITY  0.9425f // in rad/s
#define MAX_CENTRAL_DRIVE_TORQUE    300.0f     // in Nm -> the real number is 675 but we should never approach that
#define CENTRAL_DRIVE_GEAR_RATIO    540.0f
#define CENTRAL_DRIVE_OUTPUT_RATIO  1.0f        //  purely rotational
#define CENTRAL_DRIVE_POLE_PAIRS    14
#define CENTRAL_DRIVE_TORQUE_CONSTANT   .0641f   // Nm/A

#define MAX_LINEAR_ACTUATOR_VELOCITY 560.0f     // this should be change
#define MAX_LINEAR_ACTUATOR_TORQUE      10.0f
#define LINEAR_ACTUATOR_GEAR_RATIO      15.0f
#define LINEAR_ACTUATOR_OUTPUT_RATIO    1.0f    // this should be the pitch of the screw
#define LINEAR_ACTUATOR_POLE_PAIRS      14      // update this
#define LINEAR_ACTUATOR_TORQUE_CONSTANT .0341f

#define MAX_SMALL_CONVEYOR_VELOCITY 4900.0f
#define MAX_SMALL_CONVEYOR_TORQUE   .24f
#define SMALL_CONVEYOR_GEAR_RATIO    1.0f
#define SMALL_CONVEYOR_OUTPUT_RATIO  1.0f
#define SMALL_CONVEYOR_POLE_PAIRS   7
#define SMALL_CONVEYOR_TORQUE_CONSTANT .0367f

#define MAX_LARGE_CONVEYOR_VELOCITY 230.0f
#define MAX_LARGE_CONVEYOR_TORQUE    15.0f
#define LARGE_CONVEYOR_GEAR_RATIO   21.0f
#define LARGE_CONVEYOR_OUTPUT_RATIO 1.0f
#define LARGE_CONVEYOR_POLE_PAIRS   7
#define LARGE_CONVEYOR_TORQUE_CONSTANT  .0341f

#define MAX_VIBRATOR_VELOCITY   6000.0f
#define MAX_VIBRATOR_TORQUE     .13f
#define VIBRATOR_GEAR_RATIO     1.0f
#define VIBRATOR_OUTPUT_RATIO   1.0f
#define VIBRATOR_POLE_PAIRS     1
#define VIBRATOR_TORQUE_CONSTANT    .0367f

#define MAX_OUTRIGGER_VELOCITY  10.0f
#define MAX_OUTRIGGER_TORQUE    10.0f
#define OUTRIGGER_GEAR_RATIO    1.0f
#define OUTRIGGER_OUTPUT_RATIO  1.0f
#define OUTRIGGER_POLE_PAIRS    1
#define OUTRIGGER_TORQUE_CONSTANT   1.0f


#define ROBOT_AXLE_LENGTH 0.5f
#define ROBOT_MAX_SPEED 0.5f

#endif
