

#define FRONT_LEFT_WHEEL_ID 0
#define FRONT_RIGHT_WHEEL_ID 1
#define BACK_RIGHT_WHEEL_ID 2
#define BACK_LEFT_WHEEL_ID 3
#define WHEEL_CAN_NETWORK ("can0")

#define MAX_WHEEL_VELOCITY 2.0f
#define MAX_WHEEL_TORQUE 176.0f
#define WHEEL_GEAR_RATIO 181.4f
#define WHEEL_OUTPUT_RATIO .3048f
#define WHEEL_POLE_PAIRS 1
#define WHEEL_TORQUE_CONSTANT 4.0f
